name: beforer matrix example

on: 
    push:
    workflow_dispatch: 

jobs:
    deploy-on-ubuntu:
        runs-on: ubuntu-latest
        steps:
        - name: echo docker details
          run: docker info

        - name: run images
          run: docker run hello-world
    
    deploy-onwindows:
            runs-on: windows-latest
            steps:
            - name: echo docker details
              run: docker info
            - name: run images
              run: docker run hello-world
              
        




