name: matrix implementation 

on:
    push:
    workflow_dispatch: 

jobs:
    deploy:
        strategy:
            
           matrix:
                version: [10,12]
                os: [ubuntu-latest,windows-latest]
                images: [hello-world,alpine]
                exclude:
                  - images: alpine
                    os: windows-latest
                include:
                  - images: amd64/alpine
                    os: ubuntu-latest
        runs-on: ${{ matrix.os }}
        steps:
        - name: echo docker details 
          run:  docker info
        - name: run image on ${{matrix.os}} with ${{matrix.images}}
          run:  docker run ${{ matrix.images }}
          
            
            